@host = localhost
# TODO https
@port = 8888
@sheme = http
@domain = {{sheme}}://{{host}}:{{port}}

### Get all superheroes
GET {{domain}}/api/v1/superheroes HTTP/1.1

### Get superhero
GET {{domain}}/api/v1/superheroes/1 HTTP/1.1
Accept: application/json

### Add new superhero
POST {{domain}}/api/v1/superheroes HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "id": 1,
  "alias": "Der Admin jklhjklö ",
  "realName": "Alex Admin ddbbb",
  "dateOfBirth": "1987-07-22",
  "gender": "Male",
  "occupation": "Administrator"
}

### Update superhero
PUT {{domain}}/api/v1/superheroes/1 HTTP/1.1
Accept: application/json
Content-Type: application/json

{

  "realName": "Alex Admin ddbbb",
  "dateOfBirth": "1987-07-22",
  "gender": "Male",
  "occupation": "Administrator"
}

### Update superhero
PUT {{domain}}/api/v1/superheroes/1 HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "alias": "Der Admin jklhjklö ",
  "realName": "Alex Admin ddbbb",
  "dateOfBirth": "1987-07-22",
  "gender": "Male",
  "occupation": "Administrator"
}

### Delete superheo (mark as deleted)
DELETE {{domain}}/api/v1/superheroes/1 HTTP/1.1