@host = localhost
# TODO https
@port = 8888
@sheme = http
@domain = {{sheme}}://{{host}}:{{port}}

### Get all superheroes
GET {{domain}}/api/v1/superheroes HTTP/1.1

### Get all superheroes with page
GET {{domain}}/api/v1/superheroes?page=11 HTTP/1.1

### Get superhero 404
GET {{domain}}/api/v1/superheroes/666 HTTP/1.1
Accept: application/json

### Get superhero
GET {{domain}}/api/v1/superheroes/6 HTTP/1.1
Accept: application/json

### Add new superhero
POST {{domain}}/api/v1/superheroes HTTP/1.1
Accept: application/json
Content-Type: application/json

{
 
  "realName": "Alex Admin ddbbb",
  "dateOfBirth": "1987-07-22",
  "gender": "Male",
  "occupation": "Administrator"
}

### Update superhero - should be ok
PUT {{domain}}/api/v1/superheroes/1 HTTP/1.1
Accept: application/json
Content-Type: application/json

{

  "realName": "Alex Admin ddbbb",
  "dateOfBirth": "1987-07-22",
  "gender": "Male",
  "occupation": "Administrator"
}


### Update superhero
PUT {{domain}}/api/v1/superheroes/1 HTTP/1.1
Accept: application/json
Content-Type: application/json

{
 "alias": "The Wise Owl",
  "realName": "Alex Admin ddbbb",
  "dateOfBirth": "1987-07-22",
  "gender": "Male",
  "occupation": "Administrator"
}

### Delete superheo (mark as deleted)
DELETE {{domain}}/api/v1/superheroes/4 HTTP/1.1