@host = localhost
# todo https
@port = 8888
@sheme = http
@domain = {{sheme}}://{{host}}:{{port}}

### Get all superheroes
GET {{domain}}/api/v1/superheroes/

### Get superhero
GET {{domain}}/api/v1/superheroes/666
Accept: application/json