spring.application.name: superhero
spring:
    config:
        activate:
            on-profile: test
    shell:
        interactive:
            enabled: false
    jpa:
        properties:
            hibernate:
                ddl-auto: create-drop
                format_sql: true
                highlight_sql: true
    datasource:
        driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    sql:
        init:
            mode: always
    liquibase:
        enabled: true
        change-log: classpath:/db/migrations/changelog-master.yaml
debug: true
abach42:
    superhero:
        oci:
            testcontainer:
                imageName: postgres:latest
junit:
    jupiter:
        execution: 
            parallel:
                enabled: true
                config:
                    strategy: fixed
                    fixed:
                        parallelism: 8
                mode:
                    default: concurrent
                    classes:
                        default: concurrent