com.abach42.superhero:
    security:
        jwt:
            # must be at least 256 bits
            token-secret: ks9lg8pubax3ctmw9aq4pz4vduxllqq4
spring:
    config:
        activate:
            on-profile: container
    datasource:
        # runs internal of docker network
        url: jdbc:postgresql://database:5432/db
        # credentaial use only for localhost (production: change and use .env)
        username: db
        password: db