services:
  postgres-db:
    container_name: postgres-superhero-db
    image: postgres:latest
    restart: always
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
      POSTGRES_DB: db
    volumes:
      - ./.data/:/var/lib/posgresql/data/
      - ./create.sql:/docker-entrypoint-initdb.d/create.sql